services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://your.domain"
      ROCKET_ADDRESS: "0.0.0.0"
    ports:
      - "80:80"
    volumes:
      - ./vw-data:/data
